### ISSUE TITLE
Errors Testing the Lambda Function

### ISSUE THREAD

**Issue by biggiemac** [cboscolo/elb2loggly#1]
I keep getting this in the output when I try to simply test the function:

{
  "errorMessage": "Process exited before completing request",
  "errorType": "TypeError: Cannot read property '0' of undefined"
}

Followed by:

START RequestId: 4b4459a1-eeb1-11e4-bd95-b14278e4e77b
Failure while running task: TypeError: Cannot read property '0' of undefined
    at exports.handler (/var/task/elb2loggly.js:90:30)
Process exited before completing request
TypeError: Cannot read property '0' of undefined

What am I missing?

**Comment by cboscolo** [comment]
Looks like that error is coming from here (elb2loggly.js:90):

```
89:   // Get the object from the event and show its content type
90:   var bucket = event.Records[0].s3.bucket.name;
```

Based on this, I would confirm that you have the lambda event source configured correctly.  BTW, it looks like the AWS console has been updated since I wrote the how-to, so the steps below are my untested guess on how to set things up in the current version of the console.

In the AWS console Lambda function list: Actions -> Add event source
Make sure:
- Event source type: S3
- Bucket: [your s3 bucket]
- Event type: Object Created

That chunk of code that parses the event should do some sanity checks on the event prior to using it.  (I'll pull this enhancement if you want to make it.)

**Comment by cboscolo** [comment]
Also, if you are testing the lambda function using the console to send it a sample event, you need to make sure the event you send it is and "S3 Put" and the contents of the event have valid elements like the bucket name.

**Comment by biggiemac** [comment]
@cboscolo Thanks for the advice on the "put" - I am now seeing this:

START RequestId: ID
2015-04-29T21:45:32.913Z        Unable to read sourcebucket/HappyFace.jpg and upload to loggly due to an error: AccessDenied: Access Denied
2015-04-29T21:45:32.933Z    ID  result: null
2015-04-29T21:45:32.974Z    ID  { [AccessDenied: Access Denied]
  message: 'Access Denied',
  code: 'AccessDenied',
  time: Wed Apr 29 2015 21:45:32 GMT+0000 (UTC),
  statusCode: 403,
  retryable: false,
  retryDelay: 30 } 'AccessDenied: Access Denied
    at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/services/s3.js:326:35)
    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:100:18)
    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:604:14)
    at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:21:12)
    at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:22:9)
    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:606:12)
    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:104:18)'
Failure while running task: ReferenceError: LOGGLY_URL is not defined
    at Response.<anonymous> (/var/task/elb2loggly.js:121:14)
    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:350:18)
    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:100:18)
    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:604:14)
    at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:21:12)
    at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:22:9)
    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:606:12)
END RequestId: 
REPORT RequestId: ID    Duration: 1438.76 ms    Billed Duration: 1500 ms    Memory Size: 128 MB Max Memory Used: 21 MB

**Comment by cboscolo** [comment]
See my second comment.  You need to send a properly formatted event if you are using the sample test invocation capability of the AWS console.

**Comment by ksac1** [comment]
I am getting: TypeError: Cannot read property '0 of undefined at exports.handler .
I am writing a lambda function in Node.js 8.10
